apps:
  g:
    name: "Google Chrome"
    executable:
      darwin: "/Applications/Google Chrome.app"
      linux: "google-chrome"
      windows: "chrome.exe"
    type: "browser"
    description: "Google Chrome browser"
  
  c:
    name: "Cursor"
    executable:
      darwin: "/Applications/Cursor.app"
      linux: "cursor"
      windows: "cursor.exe"
    type: "editor"
    description: "Cursor code editor"
  
  t:
    name: "iTerm"
    executable:
      darwin: "/Applications/iTerm.app"
      linux: "gnome-terminal"
      windows: "cmd.exe"
    type: "terminal"
    description: "Terminal application"
  
  p:
    name: "Postman"
    executable:
      darwin: "/Applications/Postman.app"
      linux: "postman"
      windows: "postman.exe"
    type: "api"
    description: "Postman API testing tool"

  w:
    name: "WeChat"
    executable:
      darwin: "/Applications/WeChat.app"
      linux: "wechat"
      windows: "wechat.exe"
    type: "chat"
    description: "WeChat"
 
  i:
    name: "IntelliJ IDEA"
    executable:
      darwin: "/Applications/IntelliJ IDEA.app"
      linux: "idea"
      windows: "idea.exe"
    type: "editor"
    description: "IntelliJ IDEA code editor"

  py:
    name: "PyCharm"
    executable:
      darwin: "/Applications/PyCharm CE.app"
      linux: "pycharm"
      windows: "pycharm.exe"
    type: "editor"
    description: "PyCharm code editor"

  k:
    name: "Kim"
    executable:
      darwin: "/Applications/Kim.app"
      linux: "kim"
      windows: "kim.exe"
    type: "chat"
    description: "Kim"

  s:
    name: "Safari"
    executable:
      darwin: "/Applications/Safari.app"
      linux: "safari"
      windows: "safari.exe"
    type: "browser"
    description: "Safari browser"
  
  d:
    name: "DBeaver"
    executable:
      darwin: "/Applications/DBeaver.app"
      linux: "dbeaver"
      windows: "dbeaver.exe"
    type: "database"
    description: "DBeaver database tool"