websites:
  g:
    name: "Google"
    url: "https://www.google.com"
    description: "Google search engine"
  
  gh:
    name: "GitHub"
    url: "https://github.com"
    description: "GitHub code repository"
  
  gpt:
    name: "ChatGPT"
    url: "https://chat.openai.com"
    description: "OpenAI ChatGPT"
  
  yt:
    name: "YouTube"
    url: "https://www.youtube.com"
    description: "YouTube video platform"
  
  tw:
    name: "Twitter"
    url: "https://twitter.com"
    description: "Twitter social media"
  
  r:
    name: "Reddit"
    url: "https://www.reddit.com"
    description: "Reddit community platform"

  ruan:
    name: "Ruan YiFeng"
    url: "https://www.ruanyifeng.com/blog/"
    description: "Ruan YiFeng's blog"